# Generated by Django 3.0.3 on 2020-03-25 08:42

# import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200, verbose_name='Name of statya')),
                # ('article_text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('article_picture', models.CharField(max_length=300, verbose_name='way of img')),
                ('article_small_text', models.TextField()),
                ('pub_date', models.DateField(verbose_name='date of pub')),
            ],
        ),
    ]
