# Generated by Django 3.0.3 on 2020-04-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_coding'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='diy',
            field=models.BooleanField(default=0, verbose_name='Категория самоделки'),
        ),
        migrations.AddField(
            model_name='article',
            name='soft',
            field=models.BooleanField(default=0, verbose_name='Категория программы'),
        ),
    ]
