# Generated by Django 3.0.3 on 2020-04-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200415_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='downloand_files',
            field=models.CharField(default='', max_length=200, verbose_name='Файлы для загрузки'),
        ),
    ]
