# Generated by Django 3.0.3 on 2020-04-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_downloand_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='downloand_files',
            field=models.CharField(blank=True, max_length=200, verbose_name='Файлы для загрузки'),
        ),
    ]
