# Generated by Django 3.0.3 on 2020-05-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='Niktech', max_length=300, verbose_name='meta тег description'),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='Niktech', max_length=100, verbose_name='meta тег title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_picture',
            field=models.TextField(default='mrrobot.jpg', verbose_name='Основная картинка'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_small_text',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(max_length=200, verbose_name='Название статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(verbose_name='Дата публикации'),
        ),
    ]
