# Generated by Django 3.0.3 on 2020-05-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20200508_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(default='Niktech NT', max_length=300, verbose_name='meta тег description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Niktech NT', max_length=100, verbose_name='meta тег title'),
        ),
    ]
