# Generated by Django 3.0.3 on 2020-07-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='diy',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='article',
            name='news',
            field=models.BooleanField(default=0, verbose_name='Категория новости'),
        ),
        migrations.AddField(
            model_name='article',
            name='something',
            field=models.BooleanField(default=0, verbose_name='Категория прочее'),
        ),
    ]
