# Generated by Django 3.0.3 on 2020-07-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20200715_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='downloand_files',
        ),
    ]
