# Generated by Django 3.0.3 on 2020-07-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_remove_article_downloand_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_picture_alt',
            field=models.TextField(default='NikTech Top', verbose_name='Тег alt для картинки'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_picture',
            field=models.ImageField(upload_to='images/', verbose_name='Основная картинка'),
        ),
    ]
