# Generated by Django 3.0.3 on 2020-07-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20200721_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='users/', verbose_name='Аватарка'),
        ),
    ]
