# Generated by Django 3.0.3 on 2020-07-22 06:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0020_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like_done',
            field=models.ManyToManyField(related_name='users_likes_main', to=settings.AUTH_USER_MODEL),
        ),
    ]
