# Generated by Django 3.0.3 on 2020-08-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0022_article_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='dislikes',
        ),
        migrations.CreateModel(
            name='IPAdressOfUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adress', models.ManyToManyField(related_name='users_ip', to='article.Article')),
            ],
        ),
    ]
