# Generated by Django 3.0.3 on 2020-08-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_auto_20200811_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipadressofuser',
            name='ip_adress_char',
            field=models.CharField(default='', max_length=16),
        ),
    ]
