# Generated by Django 3.0.3 on 2020-08-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0024_ipadressofuser_ip_adress_char'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipadressofuser',
            name='ip_adress_char',
        ),
        migrations.AddField(
            model_name='article',
            name='users_ip',
            field=models.ManyToManyField(related_name='users_ip', to='article.IPAdressOfUser'),
        ),
        migrations.RemoveField(
            model_name='ipadressofuser',
            name='ip_adress',
        ),
        migrations.AddField(
            model_name='ipadressofuser',
            name='ip_adress',
            field=models.CharField(default='', max_length=16),
        ),
    ]
