# Generated by Django 3.0.3 on 2020-08-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0026_auto_20200812_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAdressOfUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adress', models.CharField(default='', max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='users_ip',
            field=models.ManyToManyField(related_name='users_ip', to='article.IPAdressOfUser'),
        ),
    ]
