# Generated by Django 3.2.5 on 2021-10-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0027_auto_20200812_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='users_ip',
            field=models.ManyToManyField(editable=False, related_name='users_ip', to='article.IPAdressOfUser'),
        ),
    ]
