# Generated by Django 3.2.5 on 2021-10-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0028_alter_article_users_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='home', max_length=50, verbose_name='name')),
                ('description', models.TextField(default='', verbose_name='Description')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_picture_alt',
        ),
        migrations.RemoveField(
            model_name='article',
            name='coding',
        ),
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='like_done',
        ),
        migrations.RemoveField(
            model_name='article',
            name='news',
        ),
        migrations.RemoveField(
            model_name='article',
            name='soft',
        ),
        migrations.RemoveField(
            model_name='article',
            name='something',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='users_ip',
        ),
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
        migrations.DeleteModel(
            name='IPAdressOfUser',
        ),
    ]
