# Generated by Django 3.2.5 on 2021-10-25 19:49

from django.db import migrations
import markdownx.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0029_auto_20211025_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_content_md',
            field=markdownx.models.MarkdownxField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='tagArticle',
            field=multiselectfield.db.fields.MultiSelectField(choices=[], max_length=200, null=True),
        ),
    ]
