# Generated by Django 3.2.5 on 2021-10-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0030_auto_20211025_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time_to_read',
            field=models.IntegerField(default=1, verbose_name='Время чтения'),
        ),
    ]
