# Generated by Django 3.2.5 on 2021-11-05 19:36

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0031_article_time_to_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_id',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='article',
            name='tagArticle',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('python', 'python'), ('webdev', 'webdev'), ('c++', 'c++'), ('c#', 'c#'), ('base', 'base'), ('sql', 'sql')], max_length=29, null=True),
        ),
    ]
