# Generated by Django 3.2.5 on 2021-11-05 20:15

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0032_auto_20211105_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200, verbose_name='Название статьи')),
                ('product_picture', models.ImageField(upload_to='images/', verbose_name='Основная картинка')),
                ('product_small_text', models.TextField(verbose_name='Краткое описание')),
                ('article_content_md', markdownx.models.MarkdownxField(null=True)),
                ('pub_date', models.DateField(verbose_name='Дата публикации')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
            ],
        ),
    ]
