# Generated by Django 3.2.5 on 2021-11-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0033_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='avatar',
        ),
        migrations.AddField(
            model_name='products',
            name='downloads',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
    ]
